name: Linux Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    
    
jobs:
  build:
    name: Linux Build CI
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        # Might want debug once release works
        configuration: ['release'] # , 'debug']
        platform: ['x64', 'x86', 'aarch64']
        
    steps:   
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
          fetch-depth: '0'

      - name: premake
        run: |
          PREMAKE=external/slang-binaries/premake/premake-5.0.0-alpha16/bin/linux-64/premake5
          chmod u+x ${PREMAKE}
          ${PREMAKE} gmake --deps=true --no-progress=true          

      - name: Build
        run: |
          if [[ "${{matrix.platform}}" == "aarch64" ]]; then
            source .github/workflows/setup-crosscompile-arm.sh
            CC=aarch64-linux-gnu-gcc-9 CXX=aarch64-linux-gnu-g++-9 make config=${{matrix.configuration}}_${{matrix.platform}} -j`nproc`
          else
            make config=${{matrix.configuration}}_${{matrix.platform}} -j`nproc`
          fi
          
      # https://github.com/actions/upload-artifact
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: slang-glslang-linux-${{matrix.platform}}-${{matrix.configuration}}
      #    path: |
      #      bin/**/*.so
      #      README.md
            
